title: John DeWyze
email: john@dewyze.dev
description: >- # this means to ignore newlines until "baseurl:"
  John DeWyze - Software Developer
baseurl: ""
url: "https://dewyze.dev"
github_username:  dewyze
destination: /docs

highlighter: rouge
defauts:
  - scope:
      path: "assets/img"
    values:
      image: true

collections:
  passions:
    output: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  load_paths:
    - _scss
